DROP TABLE COMMENT_BBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_COMMENT;

CREATE TABLE COMMENT_BBS(
    SEQ NUMBER(10) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    SEQ_RESTAURANT NUMBER(10),

    CONTENT VARCHAR2(1000) NOT NULL,
    WDATE DATE NOT NULL,
    
    REPORT_IT NUMBER(1) NOT NULL
    
);

CREATE SEQUENCE SEQ_COMMENT
START WITH 1
INCREMENT BY 1;

ALTER TABLE COMMENT_BBS
ADD CONSTRAINT FK_COMMENT_ID FOREIGN KEY (ID)
REFERENCES MEMBER(ID);

ALTER TABLE COMMENT_BBS
ADD CONSTRAINT FK_COMMENT_SEQ_RESTAURANT FOREIGN KEY (SEQ_RESTAURANT)
REFERENCES RESTAURANT_BBS(SEQ);