DROP TABLE CS_BBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CS;

CREATE TABLE CS_BBS(
  SEQ NUMBER(10) PRIMARY KEY,
  ID VARCHAR2(50) NOT NULL,

  REF NUMBER(8) NOT NULL,
  STEP NUMBER(8) NOT NULL,
  DEPTH NUMBER(8) NOT NULL,

  TITLE VARCHAR2(200) NOT NULL,
  CONTENT VARCHAR2(4000) NOT NULL,
  WDATE DATE NOT NULL,
  TYPE NUMBER(1) NOT NULL, --공지사항인지, 답글인지 구분

  DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE SEQ_CS
START WITH 1
INCREMENT BY 1;

ALTER TABLE CS_BBS
ADD CONSTRAINT FK_CS_ID FOREIGN KEY (ID)
REFERENCES MEMBER(ID);
